sudo: required
dist: trusty
language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - doxygen
      - doxygen-latex
      - doxygen-doc

install:
    - wget https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
    - tar -xvf cmocka-1.1.0.tar.xz
    - cd cmocka-1.1.0
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..
    - make
    - sudo make install
    - cd ../..
    - rm -rf cmocka-1.1.0

script:
  - ./make_dist scclust_dist && cd scclust_dist
  - mkdir build && cd build
  - ../configure
  - make
  - cd examples/simple && make && ./simple_example.out && make clean && cd ../..
  - cd examples/ann && make && ./ann_example.out && make clean && cd ../..
  - make clean
  - cd ..
  - ./configure --enable-documentation
  - make
  - cd examples/simple && make && ./simple_example.out && make clean && cd ../..
  - make clean
  - cd ..
  - ./configure --disable-documentation
  - make
  - cd examples/simple && make && ./simple_example.out && make clean && cd ../..
  - ./clean
  - cd tests
  - ./run_tests.sh
  - ./run_tests.sh -a
  - ./complete_test.sh
